chosen_optimization_setting: custom
optimization_or_visualization: optimize
path_data: /home/localadmin/Dokumente/ptx_now_data/data/
path_optimize: FT_all_data.yaml
path_projects: /home/localadmin/Dokumente/ptx_now_data/settings/
path_result: /home/localadmin/Dokumente/ptx_now_data/results/
path_visualization: null
solver: gurobi
